server:
    servlet:
        context-path: /api

app:
    datasource:
        jdbc-url: jdbc:postgresql://localhost:5432/eddiedemo
        username: postgres
        password: password
        pool-size: 30